apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    kubernetes.io/change-cause: "beta-6.4-php8.2-fpm-alpine"
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:beta-6.4-php8.2-fpm-alpine
        ports:
        - containerPort: 80
