apiVersion: v1
kind: Pod
metadata:
  name: mosquitto-pod
spec:
  containers:
  - name: mosquitto
    image: eclipse-mosquitto
    ports:
    - containerPort: 1883
    volumeMounts:
    - name: config-volume
      mountPath: "/mosquitto/config"
    - name: secret-volume
      mountPath: "/mosquitto/secret"
  volumes:
  - name: config-volume
    configMap:
      name: mosquitto-configmap
  - name: secret-volume
    secret:
      secretName: mosquitto-secret