# Homework6 Part2
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi


---

apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: pv-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: pvc-volume
